### ISSUE TITLE
Artifact search performed on unspecified index

### ISSUE THREAD

**Issue by MickaelFontes** [falcosecurity/falcoctl#281]
**What happened**: When executing `falcoctl artifact search a` to test, the command failed and returned:

```bash
ERRO  unable to connect to registry "europe-west1-docker.pkg.dev": GET "https://europe-west1-docker.pkg.dev/v2/": GET "https://europe-west1-docker.pkg.dev/v2/token": unexpected status code 401: unauthorized: failed authentication
```
But only one index is specified. See below `falcoctl.yaml` content:

```yaml
indexes:
- name: falcosecurity
  url: https://falcosecurity.github.io/falcoctl/index.yaml
registry:
  auth:
    basic:
    - registry: europe-west1-docker.pkg.dev
      user: oauth2accesstoken
      password: [ACCESS TOKEN]
```

**What you expected to happen**: If expected `falcoctl artifact search a` to perform the search feature on the only index provided, on `falcosecurity`.

**How to reproduce it (as minimally and precisely as possible)**: See above `falcoctl.yaml` file. 

NB: May appear with any other registry listed in auth settings with other settings (not only basic - simple assumption, I did not test that).

**Anything else we need to know?**: `Client Version: 0.4.0`
